In [6]:
import numpy as np
a=np.array([[10],[50],[30]])
print(a)
print(type(a))

[[10]
 [50]
 [30]]
<class 'numpy.ndarray'>


In [2]:
print(a.shape)
# This property is being used to showcase no of rows and columns .

(3, 1)


In [3]:
print(a.ndim)
# Its shows the dimensions of the matrix.

2


In [9]:
AB=np.array([1,2,6,4,7,8])
print(AB)
DC=AB.reshape([3,2])# we are reshaping it , and remember valid row and column pair.
print(DC)

[1 2 6 4 7 8]
[[1 2]
 [6 4]
 [7 8]]


In [8]:
a=np.arange(24)
print(a)
print(a.ndim)#we are giving dimensions to it.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [11]:
b=a.reshape(2,4,3)
print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [11]:
p=np.zeros((2,2))#ones array can also be printed in place of zeros
print(p)

[[0. 0.]
 [0. 0.]]


In [16]:
p=np.array([1,2,3,4,5], dtype=np.float32)# we converted array in float values.
print(p)

[1. 2. 3. 4. 5.]


In [12]:
#creating an indentity matrix
a=np.eye(8) #eye is used to represent number or zeros execept ones in diagonal form.
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
