In [36]:
import numpy as np # used to perform opertion on array
import pandas as pd 
a=np.array([9,5,8,3])
print(a)
print(type(a))

[9 5 8 3]
<class 'numpy.ndarray'>


In [37]:
# list of operation that can easily performed on this.
# #ndim – It returns the dimensions of the array.
# itemsize – It calculates the byte size of each element.
# dtype – It can determine the data type of the element.
# reshape – It provides a new view.
# slicing – It extracts a particular set of elements.
# linspace – Returns evenly spaced elements.

In [41]:
print(a.ndim)
print(a.shape)
print(a.itemsize)# how it is 44
print(a.ndim)#if we put mutiple datatype then it will show some werid kind of data.
print(a.reshape)
a=np.eye(12)#sirf diagonally hi 1-1 hai baki toh zeros
print(a)
# print(a.slicing)
# print(a.linspace)in dono mai no attribute object show kar raha hai.

2
(8, 8)
8
2
<built-in method reshape of numpy.ndarray object at 0x000001D35D4A7390>
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [42]:
nishu=['5','7','string',"fortuner","hey hii"]
print(type(nishu))

<class 'list'>


In [44]:
pragya=['3','8'],["string","hey"],["hsy",8]
print(type(pragya))

<class 'tuple'>


In [45]:
import pandas as pd